<?php

namespace AppBundle\Repository;

/**
 * BlogpostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogpostRepository extends \Doctrine\ORM\EntityRepository
{
}
