<?php

namespace AppBundle\Repository;

/**
 * ConcertsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertsRepository extends \Doctrine\ORM\EntityRepository
{
}
